### ISSUE TITLE
Error with latest version of chunks in cpic utils.py

### ISSUE THREAD

**Issue by miguelj-neves** [lijunzh/yews#16]
I'm getting an error message from chunks when doing detection in array.take (line 25). I think my code must be confusing take from numpy and pytorch.
**Error message:** TypeError: take() missing 1 required positional arguments: "index"

I didn't manage to find a solution besides changing to the old version of utils.py

**Comment by lijunzh** [comment]
Can you share an example code to reproduce the error?

**Comment by miguelj-neves** [comment]
**This is the code I'm using:**
```
import numpy as np
import pickle
import os
from obspy import read
from torch import cuda
from torch import nn
from torch import load
from yews import transforms
from yews.cpic import detect
from yews.datasets.utils import stream2array
from yews.models import cpic_v1
cpic = cpic_v1

output_path = "./detection_results"
training_results = "train_b_pre_nofilt.pth.tar"

transform = transforms.Compose([
	transforms.ZeroMean(),
	transforms.SoftClip(1e-3),
	transforms.ToTensor(),
])

model_pth = load(training_results)["model"]
model = cpic(pretrained = False)
model.load_state_dict(model_pth)

if cuda.is_available():
	device = ("cuda" if cuda.is_available() else "cpu" )
	model = nn.DataParallel(model, device_ids=[0, 1])
	model.to(device)

if __name__ == "__main__":
	path = "./ES.EADA.HH?.SAC"
	pkl_output_path=output_path
	if not os.path.isdir(pkl_output_path):
		os.mkdir(pkl_output_path)
	st = read(path)
	network = st[0].stats.network
	station = st[0].stats.station
	sprate = st[0].stats.sampling_rate

	waveform = stream2array(st)
	detect_results = detect(waveform, sprate, 20, model, transform, 2, threshold=0.5, batch_size=10000)
		
	pkl_file=open(pkl_output_path + '/' +network+'_'+ station + 'detect_results.pkl','wb')
	pickle.dump(detect_results,pkl_file)
	pkl_file.close()
```

**Here is the error message:**
Traceback (most recent call last):
  File "./ml_detect.py", line 89, in <module>
    detect_results = detect(waveform, sprate, 20, model, transform, 2, threshold=0.5, batch_size=10000)
  File "/Users/mike/anaconda3/lib/python3.7/site-packages/yews/cpic/detection.py", line 45, in detect
    batch_size=batch_size)
  File "/Users/mike/anaconda3/lib/python3.7/site-packages/yews/cpic/utils.py", line 34, in compute_probs
    for batch in chunks(windows, batch_size):
  File "/Users/mike/anaconda3/lib/python3.7/site-packages/yews/cpic/utils.py", line 25, in chunks
    yield array.take(indices=range(i, range_end), axis=slice_axis)
TypeError: take() missing 1 required positional arguments: "index"

Let me know if you need the input files. Thank you

**Comment by lijunzh** [comment]
> yield array.take(indices=range(i, range_end), axis=slice_axis)
> TypeError: take() missing 1 required positional arguments: "index"

This is due to the fact that you pass a `torch.Tensor` instead of `np.Array` to this functin. Both PyTorch and Numpy has a function named `take` for their datatype. However, the API is slightly different. I do see the usage here being valid. We should add a `chunk_tensor()` function in addition to this `chunck_array()`. 

Let's correct it in a PR.
