### ISSUE TITLE
yews.datasets.MarianaFromSource

### ISSUE THREAD

**Issue by sissiautumn** [lijunzh/yews#7]
I put the event_p and event_s in the ./ 
when I used "a=yews.datasets.sac.MarianaFromSource(path='./');"
It showed "module 'yews.datasets' has no attribute 'MarianaFromSource'"
My earlier version works well, but the recent version failed. I checked both versions, MarianaFromSource is classified in the sac.py file.

**Comment by lijunzh** [comment]
@sissiautumn It has been moved to `yews.datasets.sac` module. I will eventually deprecate it and make that class as an example of package your own dataset in the example.
